# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-truforms' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-truforms
  pod 'Moya'
  pod 'Eureka'
  pod 'ImageRow', '~> 4.0'
  pod 'MaterialComponents/TextFields'
  target 'iOS-truformsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'iOS-truformsUITests' do
    # Pods for testing
  end

end
